import { ref } from 'vue'

export function useDepartment() {
  const departments = ref<any>([
    {
      name: "Umumta'lim fanlari kafedrasi",
      url: '/departments/umumtalim.jpg',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus?',
      path: '/about/department/general-education'
    },
    {
      name: 'Bugalteriya hisobi va audit kafedrasi',
      url: '/departments/bugalteriya.jpg',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus?',
      path: '/about/department/bugaltery'
    },
    {
      name: 'Harakatni tashkil etish va boshqarish kafedrasi',
      url: '/departments/logistic.jpg',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus?',
      path: '/about/department/logistic'
    },
    {
      name: 'Avtomatika, aloqa va texnologik jaroyonlarni avtomatlashtirish kafedrasi',
      url: '/departments/automatic.jpg',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus?',
      path: '/about/department/automation'
    },
    {
      name: 'Harakat tarkibi va infratuzilma ekspluatatsiyasi kafedrasi',
      url: '/departments/harakat_tarkibi.jpg',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus?',
      path: '/about/department/infrastructure'
    }
  ])
  return { departments }
}
