import { ref } from 'vue'

export function usedepEmploye() {
  const depEmployes = ref<any>([
    {
      name: 'O‘quv-uslubiy bo‘lim',
      url: '/departments/logistic.jpg',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus?',
      path: '/about/dep-employee/education-method'
    },
    {
      name: "Masofaviy ta'limni joriy etish bo‘limi",
      url: '/departments/logistic.jpg',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus?',
      path: '/about/dep-employee/distance-edu'
    },
    {
      name: 'Xalqaro aloqalar bo‘limi',
      url: '/departments/logistic.jpg',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus?',
      path: '/about/dep-employee/international'
    },
    {
      name: 'Axborot texnologiyalarini joriy etish bo‘limi',
      url: '/departments/logistic.jpg',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus?',
      path: '/about/dep-employee/it-technology'
    },
    {
      name: 'Axborot-resurs markazi',
      url: '/departments/logistic.jpg',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus?',
      path: '/about/dep-employee/arm'
    },
    {
      name: 'Amaliyot va ish beruvchilar bilan hamkorlik bo‘limii',
      url: '/departments/logistic.jpg',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus?',
      path: '/about/dep-employee/cooperation-employer'
    },
    {
      name: 'Ichki nazorat bo‘limi',
      url: '/departments/logistic.jpg',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus?',
      path: '/about/dep-employee/internal-control'
    },
    {
      name: 'Yoshlar bilan ishlash bo‘limi',
      url: '/departments/logistic.jpg',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus?',
      path: '/about/dep-employee/work-youth'
    },
    {
      name: 'Xodimlar bo‘limi',
      url: '/departments/logistic.jpg',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus?',
      path: '/about/dep-employee/employes'
    },
    {
      name: 'Buxgalteriya bo‘limi',
      url: '/departments/logistic.jpg',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus?',
      path: '/about/dep-employee/bugaltery'
    },
    {
      name: 'Devonxona bo‘limi',
      url: '/departments/logistic.jpg',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus?',
      path: '/about/dep-employee/registry'
    },
    {
      name: 'O‘quvchilar turar joyi',
      url: '/departments/logistic.jpg',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus?',
      path: '/about/dep-employee/residence-students'
    },
    {
      name: 'Texnik foydalanish va xo‘jalik bo‘limi',
      url: '/departments/logistic.jpg',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus veniam voluptatum earum ullam et nihil doloremque, error soluta itaque deleniti ratione dolorem saepe neque vero quos nostrum possimus. Sapiente id velit nulla aut tenetur quaerat quia fugiat placeat eum? Praesentium aliquid tempora eaque voluptatem, eius quasi, nostrum, provident fugiat distinctio architecto quod beatae deserunt doloribus nulla numquam magnam quaerat. Quae perspiciatis earum laudantium deleniti eius minus aut, exercitationem reiciendis dolore, nisi dignissimos dolorem cumque tenetur suscipit nulla sint neque molestiae nostrum sunt repudiandae praesentium nobis error? Fugit itaque exercitationem repudiandae, officia aliquam ipsa dolorem. Odio doloribus eveniet, eius, soluta vitae magnam voluptas hic porro amet minus consequatur quam nemo ut dolore fuga quaerat quas est provident id dolorum sint! Possimus?',
      path: '/about/dep-employee/technical-economy'
    }
  ])
  return {depEmployes}
}
